# Generated by Django 3.1.7 on 2021-03-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('Total_Cases', models.IntegerField()),
                ('New_Cases', models.IntegerField()),
                ('Total_Deaths', models.IntegerField()),
                ('New_Deaths', models.IntegerField()),
            ],
        ),
    ]
